version: '3.8'

services:
  postgres:
    build:
      context: ./docker
      dockerfile: Dockerfile-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  server:
    build:
      context: ./docker
      dockerfile: Dockerfile-server
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  client:
    build:
      context: ./docker
      dockerfile: Dockerfile-client
    ports:
      - "5173:5173"

volumes:
  pgdata:
